projects:
  enkasPay:
    schemaPath: amplify/backend/api/enkasPay/build/schema.graphql
    includes:
      - ''
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: .
        region: us-east-1
        apiId: null
        maxDepth: 2
